tasks:
  - init: gem install bundler -v 2.0.1 && bundle install && bundle exec rake generate
ports:
  - port: 4000
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
    addLabel: false
